language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm install -g gulp@4.0.2
env:
  global:
    secure: XXXXXXXXXX
script: npm run build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: dist
  on:
    branch: master
  edge: true